language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" LINT_CHECK="0" EXCLUDE="mrp_barcode,stock_picking_no_over_scan,helpdesk_ticket_to_task,helpdesk_fieldservice,agreement_helpdesk,helpdesk_stock,helpdesk_scope,helpdesk_ticket_type_default_priority,helpdesk_phone,fieldservice_helpdesk_stock,agreement_sale_subscription,helpdesk_ticket_parent,helpdesk_fieldservice_agreement,helpdesk_resolution"
  - TESTS="1" ODOO_REPO="odoo/odoo" LINT_CHECK="0" EXCLUDE="mrp_barcode,stock_picking_no_over_scan,helpdesk_ticket_to_task,helpdesk_fieldservice,agreement_helpdesk,helpdesk_stock,helpdesk_scope,helpdesk_ticket_type_default_priority,helpdesk_phone,fieldservice_helpdesk_stock,agreement_sale_subscription,helpdesk_ticket_parent,helpdesk_fieldservice_agreement,helpdesk_resolution"

install:
  - git clone --depth=1 https://github.com/ursais/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success

